Integrate FE login and register to API
Glints-007/Attendance-FE pull request #2
Opened 2021-09-20 12:43 UTC by raendyelvicar

Did you write good & comprehensive specs? ⭐️

What's this PR do ? ⭐️
Integrate FE login and register to API

What are the relevant tickets ? ⭐️
https://www.notion.so/prawito/Integrate-Auth-Page-User-with-API-2eb75942b4174407a082f967a853403e

Where should the reviewer start ?

How should this be manually tested ?

What is the Dockup URL ?

Any background context you want to provide ?

Any deployment note (migrations, new envs, rake tasks, cron) ?

Screenshots (if appropriate)
![image](https://user-images.githubusercontent.com/33620761/134004118-77b1c669-4f52-41a3-8771-c2c6ef0abee6.png)

![image](https://user-images.githubusercontent.com/33620761/134004211-5382740a-907e-417d-8216-cd13ec076332.png)

Definition of Done:

[ ] Specs / Tests are adequate ? ⭐️

[ ] Changes conform with code quality tools (Rubocop, Reek, Brakeman) ? ⭐️

[ ] Does this PR require Database changes ?

[ ] Does this PR require monitoring after deployment (Scout, logs, Sentry, etc) ?

[ ] Does this PR require a regression test by QA ? All fixes require a regression test.

[ ] Does this add new dependencies ? (network setup, new 3rd party services)

2021-09-20 14:20 UTC, chaterinamf approved these changes

2021-09-20 14:20 UTC, herulhidayat approved these changes

2021-09-21 01:22 UTC, rahmatullah5 requested changes

2021-09-21 02:30 UTC, raendyelvicar commented on src/Actions/user.actions.js
> +                    // history.push('/dashboard');
Okaay kak

2021-09-21 02:31 UTC, raendyelvicar commented on src/Actions/user.actions.js
> +                    console.log(user);
Okaay got it

2021-09-21 02:32 UTC, raendyelvicar commented on src/Services/user.service.js
> +    return await fetch("https://floating-journey-97236.herokuapp.com/api/v1/register", requestOptions).then(handleResponse);
Okay kak, i'll try

2021-09-21 17:48 UTC, raendyelvicar commented
All done

2021-09-22 04:03 UTC, rahmatullah5 approved these changes

2021-09-22 04:03 UTC, merged