Layout/dashboard clock in out
Glints-007/Attendance-FE pull request #4
Opened 2021-09-27 13:08 UTC by herulhidayat

Did you write good & comprehensive specs? ⭐️

What's this PR do ? ⭐️
Add layout for dashboard clock in clock out
What are the relevant tickets ? ⭐️
https://www.notion.so/prawito/Create-Clock-in-clock-out-page-for-front-end-3641cd26d2aa4210b7182aad57e6d20d
Where should the reviewer start ?

How should this be manually tested ?

What is the Dockup URL ?

Any background context you want to provide ?

Any deployment note (migrations, new envs, rake tasks, cron) ?

Screenshots (if appropriate)
![image](https://user-images.githubusercontent.com/47564314/134914242-0744018d-0589-4795-a982-942ef1a38bed.png)

Definition of Done:

[ x ] Specs / Tests are adequate ? ⭐️

[ x ] Changes conform with code quality tools (Rubocop, Reek, Brakeman) ? ⭐️

[ x ] Does this PR require Database changes ?

[ x ] Does this PR require monitoring after deployment (Scout, logs, Sentry, etc) ?

[ x ] Does this PR require a regression test by QA ? All fixes require a regression test.

[ v ] Does this add new dependencies ? (network setup, new 3rd party services)

2021-09-27 17:34 UTC, rahmatullah5 requested changes

2021-09-27 17:34 UTC, rahmatullah5 commented on src/Components/AttendanceClock.js
> +    <>
what is this for ?

2021-09-27 17:34 UTC, rahmatullah5 commented on src/Components/AttendanceLog.js
> +// import './AttendanceLog.css';
please remove unused code.

2021-09-28 03:18 UTC, herulhidayat commented on src/Components/AttendanceClock.js
> +    <>
"<>" is a short syntax from "<React.Fragment>"

2021-09-28 12:48 UTC, rahmatullah5 commented on src/Components/AttendanceClock.js
> +    console.log(users);
Please remove console log from production.

2021-09-28 12:50 UTC, rahmatullah5 commented on src/Components/TableComponent.js
>        {/* <BootstrapTable
Please remove unused code

2021-09-28 12:52 UTC, rahmatullah5 commented on src/Components/TableComponent.js
>        {/* <BootstrapTable
remove unused code

2021-09-29 14:56 UTC, rahmatullah5 approved these changes

2021-09-30 11:42 UTC, chaterinamf approved these changes

2021-09-30 12:04 UTC, merged

2021-09-30 12:05 UTC, fknraini approved these changes